config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :models do
    resources :model_types
  end

  post 'models/:model_id/model_types_price/:id' => 'model_types#model_types_price', as: :model_type

end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :organization
  has_many :model_types

  validates :name, presence: true, uniqueness: true

  before_create do
    self.slug = name.downcase.gsub(" ", "-")
  end

  def to_param
    slug
  end

end

app/models/model_type.rb
class ModelType < ActiveRecord::Base
  include Pricing
  belongs_to :model

  validates :name, presence: true, uniqueness: true

  before_create do
    self.slug = name.downcase.gsub(" ", "-")
  end

  def to_param
    slug
  end

  def total_price base_price = nil
		base_price = base_price || self.base_price
		policy = self.model.organization.pricing_policy
		Pricing.pricing_calc policy, base_price
	end

  def as_json(options={})
    return_json = super
    if options.has_key? :base_price
      price = self.total_price(options[:base_price]).to_s
      return_json[:total_price] = price
    end
    return return_json
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :models
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate


  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :slug, :organization_id)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
  <%= f.label :Organization %><br>
  <%= f.collection_select(:organization_id, Organization.all, :id, :public_name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.name %></td>
        <td><%= model.slug %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_model_path(model) %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @model.name %>
  <strong>Organization:</strong>
  <%= @model.organization.public_name if @model.organization %>
</p>

<h3>Add a model type</h3>
<%= form_for([@model, @model.model_types.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :model_type_code %><br>
    <%= f.text_field :model_type_code %>
  </div>
  <div class="field">
    <%= f.label :base_price %><br>
    <%= f.text_field :base_price %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>