config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :models do
    resources :model_types
  end

  post 'models/:model_id/model_types_price/:id' => 'model_types#model_types_price', as: :model_type

end

app/controllers/model_types_controller.rb
class ModelTypesController < ApplicationController
  before_action :set_model_type, only: [:show, :model_types_price]
  skip_before_filter :verify_authenticity_token, only: [:model_types_price]


  # GET /model_types
  # GET /model_types.json
  def index
    models = Model.all.to_json(:include => {:model_types => {:only => [:name], :methods => [:total_price]}}, :only => [:name])
    respond_to do |format|
      format.json { render json: {models: JSON.parse(models)} , location: @model_type }
    end
  end

  def model_types_price
    model_type = @model_type.to_json(:only => [:name], :methods => [:total_price], :base_price => params[:base_price])
    respond_to do |format|
      format.json { render json: {:model_type => model_type}, location: nil}
    end
  end

  # GET /model_types/1
  # GET /model_types/1.json
  def show
  end

  # GET /model_types/new
  def new
    @model_type = ModelType.new
    @model = Model.find_by_slug(params[:model_id])
  end

  # GET /model_types/1/edit
  def edit
    @model = Model.find_by_slug(params[:model_id])
    @model_type = @model.model_types.find_by_slug(params[:id])
  end

  # POST /model_types
  # POST /model_types.json
  def create
    @model = Model.find_by_slug(params[:model_id])
    @model_type = ModelType.new(model_type_params)

    respond_to do |format|
      if @model_type.save
        format.html { redirect_to [@model, @model_type], notice: 'Model type was successfully created.' }
        format.json { render :show, status: :created, location: @model_type }
      else
        format.html { render :new }
        format.json { render json: @model_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_types/1
  # PATCH/PUT /model_types/1.json
  def update
    @model = Model.find_by_slug(params[:model_id])
    @model_type = @model.model_types.find_by_slug(params[:id])

    respond_to do |format|
      if @model_type.update(model_type_params)
        format.html { redirect_to [@model, @model_type], notice: 'Model type was successfully updated.' }
        format.json { render :show, status: :ok, location: @model_type }
      else
        format.html { render :edit }
        format.json { render json: @model_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_types/1
  # DELETE /model_types/1.json
  def destroy
    @model = Model.find_by_slug(params[:model_id])
    @model_type = @model.model_types.find_by_slug(params[:id])
    @model_type.destroy

    respond_to do |format|
      format.html { redirect_to model_model_types_url, notice: 'Model type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_type
      @model_type = ModelType.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_type_params
      params.require(:model_type).permit(:name, :slug, :model_type_code, :base_price, :model_id)
    end
end

app/helpers/model_types_helper.rb
module ModelTypesHelper
end

app/views/model_types/_form.html.erb
<%= form_for([@model, @model_type]) do |f| %>
  <% if @model_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model_type.errors.count, "error") %> prohibited this model_type from being saved:</h2>

      <ul>
      <% @model_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.hidden_field :model_id, :value => @model.id %><br>
  </div>

  <div class="field">
    <%= f.label :model_type_code %><br>
    <%= f.text_field :model_type_code %>
  </div>

  <div class="field">
    <%= f.label :base_price %><br>
    <%= f.text_field :base_price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/model_types/edit.html.erb
<h1>Editing Model Type</h1>

<%= render 'form' %>

<%= link_to 'Show', [ @model_type.model, @model_type ] %> |
<%= link_to 'Back', model_model_types_path %>

app/views/model_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Model Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Model type code</th>
      <th>Base price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @model_types.each do |model_type| %>
      <tr>
        <td><%= model_type.name %></td>
        <td><%= model_type.slug %></td>
        <td><%= model_type.model_type_code %></td>
        <td><%= model_type.base_price %></td>
        <td>
          <%= link_to 'Show', [model_type.model, model_type] %>
        </td>
        <td>
          <%= link_to 'Edit', edit_model_model_type_path(model_type.model, model_type) %>
        </td>
        <td>
          <%= link_to 'Destroy', [model_type.model, model_type], :confirm => 'Are you sure?', method: :delete %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model type', new_model_model_type_path %>

app/views/model_types/new.html.erb
<h1>New Model Type</h1>

<%= render 'form' %>

<%= link_to 'Back', model_model_types_path %>

app/views/model_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @model_type.name %>
</p>

<p>
  <strong>Model type code:</strong>
  <%= @model_type.model_type_code %>
</p>

<p>
  <strong>Base price:</strong>
  <%= @model_type.base_price %>
</p>

<%= link_to 'Edit', edit_model_model_type_path(@model_type.model, @model_type) %> |
<%= link_to 'Back', model_model_types_path %>